---
- name: Including append_clientlist.yaml
  include: append_clientlist.yaml
  tags:
    - append_clientlist

- name: Including install.yaml OpenVPN tasks
  include: install.yaml

- name: Verifying easyrsa exist
  stat:
    path: "/{{ base_directory }}/easy-rsa/easyrsa"
  register: rsa

- name: Including easy-rsa.yaml for OpenVPN setup
  include: easy-rsa.yaml
  when: not rsa.stat.exists

- name: Including server_keys.yaml for OpenVPN setup
  include: server_keys.yaml

- name: Including config.yaml for OpenVPN setup
  include: config.yaml

- name: Dependecies for password authentication
  include: password_dependency.yaml
  when: password_enable

- name: Including client_keys.yaml for OpenVPN setup
  include: client_keys.yaml
  when: not password_enable
  tags:
    - generate_client_keys

- name: Including client_keys.yaml for OpenVPN setup with password
  include: client_passwd_keys.yaml
  when: password_enable
  tags:
    - generate_client_keys

- name: Including revoke.yaml for OpenVpn setup
  include: revoke.yaml
  tags:
    - revoke_client_keys

- name: Including firewall.yaml for OpenVPN setup
  include: firewall.yaml
...
